name: Analyze, Test and Build

on:
  push:
    branches:
    - master
  pull_request:

jobs:

  lint:
    name: Analyze the code.
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with version 2.2.3
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          channel: stable

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update dependencies
        run: flutter pub get

      - name: Analyze the code
        run: flutter analyze 
